### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by SergeyDjam** [sanzoghenzo/markdownr#17] opened 2022-09-05 18:14 UTC
Only reset connection by peer, and end 

everytime

v1.3.0 f-droid

**Comment by sanzoghenzo** [comment] 2022-09-06 06:57
Hi @SergeyDjam , I'm sorry it doesn't work for you.
I think i need more information to check this an (hopefully) fix it.
What android version are you on?
Does it happen both when you share an url from an app and when you specify an url by hand and press the convert button?

**Comment by SergeyDjam** [comment] 2022-09-06 08:57
Hello.
Android 12 MIUI 13 POCO x3 GT
LineageOS 19 ASUS Zenfone PRO 

Press convert button
All URLs

**Comment by sanzoghenzo** [comment] 2023-09-27 17:50
Hi @SergeyDjam,
sorry for not reaching back earlier.
Did you solve the issue by any chance?
My guess is a poor internet connection, or some misconfiguration on the android side, or maybe some app that acts as VPN...
I don't think this is related to my app, since I'm using very popular libaries to do the network stuff, and so far I couldn't reproduce your issue.

**Comment by sanzoghenzo** [comment] 2023-10-29 22:29
Going to close this, feel free to reopen it if you still encounter the issue with newer versions of the app.

**Closed by sanzoghenzo** 2023-10-29 22:29 UTC
