### ISSUE TITLE
Twitter Support

### ISSUE THREAD

**Issue by Medullitus** [sanzoghenzo/markdownr#70] opened 2024-02-24 00:45 UTC
Hello. It's not working on Twitter. It's because Twitter requires Java? If so can you make a toggle to turn Java on to make it work with Twitter?

**Comment by sanzoghenzo** [comment] 2024-02-24 08:06
Hi @Medullitus ,the problem is that X now requires users to login to see any of the tweets. This is a duplicate of #30 , see that issue for more info.
Closing this.

**Closed by sanzoghenzo** 2024-02-24 08:06 UTC
